// Consider all integer combinations of ab for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:

// 22=4, 23=8, 24=16, 25=32
// 32=9, 33=27, 34=81, 35=243
// 42=16, 43=64, 44=256, 45=1024
// 52=25, 53=125, 54=625, 55=3125
// If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:

// 4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125

// How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

#include <iostream>
#include <set>
#include <cmath>
#include <math.h>

using namespace std;

uint64_t customPow(uint64_t base, uint64_t exponent) {
    uint64_t result = 1;
    for (uint64_t i = 0; i < exponent; ++i) {
        result *= base;
    }
    return result;
}
int euler29(int N){
    set<uint64_t> CombinationsSet;
    for(int i = 1; i <= N; i++){
        for(int j = 1; j <= N; j++){
            uint64_t value = j * log(i);
            cout<<"i = "<< i << "\t j = " << j << "\t value = "<< value <<endl;
            CombinationsSet.insert(customPow(i, j));
        }
    }
    return CombinationsSet.size();
}

int main(){
    int N = 100;
    int size;
    size = euler29(N);
    cout<<size<<endl;
    return 0;
}
